name: Salesforce Deployment to Dev Org

on:
  push:
    branches:
      - main
    paths:
      - '**/*' # Triggers the workflow on any changes within the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        run: |
          npm install -g sfdx-cli

      - name: Authenticate to Dev Org
        run: |
          sfdx force:auth:jwt:grant --clientid ${{ secrets.CLIENT_ID }} --jwtkeyfile ${{ secrets.SECRET_KEY }} --username ${{ secrets.YOUR_USERNAME }} --setdefaultdevhubusername -a DevHub --instanceurl https://mysba--playground.sandbox.my.salesforce.com

      - name: Deploy to Dev Org
        run: |
          sfdx force:source:deploy -p force-app -u DevHub -w 10 # Assuming 'force-app' is the directory containing your Salesforce metadata

      # Additional steps if needed (e.g., running tests, etc.)
